//TODO FÜR ABGABE ÄNDERN
const SERVER_URI = 'http://localhost:3000';
const UPDATE_INTERVAL = 1000 * 60;// one minute

const TEMPERATURE_COLOR = 'rgb(204,0,112,0.7)';
const HUMIDITY_COLOR = 'rgb(0,39,191,0.6)';
const AIRPRESSURE_COLOR = 'rgb(0,204,109,0.8)';

module.exports = {
  'SERVER_URI': SERVER_URI,
  'UPDATE_INTERVAL': UPDATE_INTERVAL,
  'TEMPERATURE_COLOR': TEMPERATURE_COLOR,
  'AIRPRESSURE_COLOR': AIRPRESSURE_COLOR,
  'HUMIDITY_COLOR': HUMIDITY_COLOR,
};
